package com.stocksexchange.android.model

enum class SettingId {

    SIGN_OUT,
    CHANGE_PIN,
    AUTHENTICATION_SESSION_DURATION,
    FINGERPRINT_UNLOCK,
    FORCE_AUTHENTICATION_ON_APP_STARTUP,
    APP_VERSION,
    LANGUAGE,
    FIAT_CURRENCY,
    KEEP_SCREEN_ON,
    RESTORE_DEFAULTS,
    PUSH_NOTIFICATION,
    NOTIFICATION_REPORT,
    ANIMATE_CHARTS,
    BULLISH_CANDLE_STICK_STYLE,
    BEARISH_CANDLE_STICK_STYLE,
    ZOOM_IN_ON_PRICE_CHART,
    DEPTH_CHART_LINE_STYLE,
    HIGHLIGHT_ORDERBOOK_REAL_TIME_UPDATES,
    HIGHLIGHT_NEW_TRADES_REAL_TIME_ADDITION,
    DEVICE_METRICS,
    CLEAR_USER_DATA,
    ANALYTICS_TOASTS

}